---
# tasks file for deploy

- name: remove default configs
  file:
    path: "/etc/nginx"
    state: absent

- name: add nginx config
  copy:
    src: config/
    dest: /etc/nginx
    owner: root
    group: root